# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest



steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: JFrogNpm@1
  inputs:
    command: 'install'
    artifactoryConnection: 'artifactory v22'
    sourceRepo: 'npm-npm'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'


- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'artifactory v22'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    excludeEnvVars: '*password*;*psw*;*secret*;*key*;*token*;*auth*;'

- task: JFrogBuildPromotion@1
  inputs:
    artifactoryConnection: 'artifactory v22'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    targetRepo: 'npm-npm'
    status: 'Released'
    comment: 'Promoting release candidate'
#    sourceRepo: 'Dev1-local'
    includeDependencies: true
    copy: false
    dryRun: false